:PROPERTIES:
:ID:       56512C1A-C615-4C7A-8A57-4134C3661DF5
:END:
#+HUGO_BASE_DIR: ../
#+TITLE: Cloud Native Definition
#+DATE: <2021-07-20 Tue 10:55>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
#+BEGIN_QUOTE
Cloud native technologies empower organizations to build and run scalable
applications in modern, dynamic environments such as public, private, and hybrid
clouds. Containers, service meshes, microservices, immutable infrastructure, and
declarative APIs exemplify this approach.

These techniques enable loosely coupled systems that are resilient, manageable,
and observable. Combined with robust automation, they allow engineers to make
high-impact changes frequently and predictably with minimal toil.

The Cloud Native Computing Foundation seeks to drive adoption of this paradigm
by fostering and sustaining an ecosystem of open source, vendor-neutral
projects. We democratize state-of-the-art patterns to make these innovations
accessible for everyone. ([[https://github.com/cncf/toc/blob/main/DEFINITION.md][via]])
#+END_QUOTE
* Containers
* Service meshes
* Microservices
* Immutable infrastructure
* Declarative APIs
