#+HUGO_BASE_DIR: ../
#+TITLE: DR
#+DATE: <2021-05-15 Sat 17:02>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
* Introduction

#+begin_quote
As an ordinary engineer, I was writing the DR scripts then in Japan.
#+end_quote

The technology updating is fast and exciting!

I'm not young anymore, and I always hope that I can produce something memorable.

* Solution Requirements/Design/Describe the Design
*** Before we started the realistic, we took much time on the design.

Writing a program is the different concept in design software. Design is the
place where software quality is established. Before starting of designing
software, the requirements should be analyzed and specified first.

In the software design process, design engineering is the one of the concept.
While beginning software, requirements have been analyzed and modeled. This
model can be accessed for quality and improved before code is generated.

In a software engineering context, the first need is to develop the models of
program, but not the program themselves.

*** Software design is different from coding.

At first it is very clear that, design is not coding and coding is not design.
It is created from program components.

Design is the description of the logic, which is used in solving the problem.
Coding is the language specification which is implementation of the design.  It
runs on the computer and, provides the expected result.  (via
https://www.chegg.com/homework-help/software-engineering-8th-edition-chapter-12-solutions-9780078022128)

*** What is a good design?

A good design should be the process of envisioning and defining software
solutions to one or more sets of problems, and you must agree that one of the
main components of software design is the software requirements analysis. while
in our project, it comes from part of specifications from customer, also, since
what we are working is kind of CA components, that should be considered during
our whole process of solution design, I mean, we need to think about making that
work better based on our product, our official solution.

Once we have a clear picture on the requirements analysis, we should get a
couple of problem lists to solve, this is important, some of them might be the
items existed in the punchlist/user storys later, and each of them should be
traceable and reflected in requirements and design.

After that, we can continue the solution design, design is kind of process and
model, if you are working within a design team, please understand that multiple
designs for the same problem can exist and will exist, while if you are working
as a solo player, try to explain that to yourself could be helpful for you to
find something different, like Rubber Duck Debugging from The Pragmatic
Programmer.

*** Design is not coding, coding is not design.
* timeplan/gtd
* roadmap
* risk analysis
* user story
* Bash or Python
* git/rosetta/pipeline
* editor
* start coding
* test
* change request
* release
* presentation/handover
