#+HUGO_BASE_DIR: ../
#+TITLE: Encryption
#+DATE: <2021-05-03 Mon 17:24>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: encryption
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
Encryption is the method by which information is converted into secret code that
hides the information's true meaning. The science of encrypting and decrypting
information is called cryptography. In computing, unencrypted data is also known
as plaintext, and encrypted data is called ciphertext.
* Cryptomator
- https://cn.apkjam.com/cryptomator.html
- https://jsntn.com/software/portable-cryptomator.html
** Mountain Duck
Mountain Duck lets you mount server and cloud storage as a disk in Finder on
macOS and the File Explorer on Windows. Open remote files with any application
and work like on a local volume.

It supports the Cryptomator Vaults - Transparent client-side encryption using
Cryptomator interoperable vaults.

-> https://mountainduck.io
* Password
KeePass https://haikebang.com/passphrase.html
* Saferoom
https://cn.apkjam.com/60s/saferoom.html
* TrueCrypt/VeraCrypt/EDS/CryptoDisk
- [[https://jsntn.com/software/2014/06/01/truecrypt.html][TrueCrypt is not secure]]
- [[https://cn.apkjam.com/eds.html][EDS]]
- [[file:veracrypt-on-macos.org][VeraCrypt on MacOS]]
- [[https://github.com/jsntn/windows-veracrypt-volume-launcher][Windows VeraCrypt Volume Launcher]]
* Read More
https://haikebang.com/secure-portable.html
