#+HUGO_BASE_DIR: ../
#+TITLE: How To Take Smart Notes
#+DATE: <2021-07-17 Sat 22:01>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
* 卢曼的“卡片盒”与传统的卡片笔记的最大区别是什么呢？
我之前在《纳博科夫的卡片》等文章中，曾介绍过纳博科夫等人的卡片写作法。那么，卢曼
与他们的最大区别是什么呢？

——多了一个盒子。

传统的卡片写作法，像纳博科夫，是只使用一个盒子，用一个盒子来保存自己写作的内容。
而卢曼多了一个盒子，对自己卡片写作的内容进行索引和整理。如果说纳博科夫的卡片写作
法特别合适创意写作，比如写小说、诗歌、散文等等；那么卢曼卡片盒写作法则尤其合适学
术写作与信息密度大的写作，比如论文、学术专著与长篇科普等。

从认知科学角度来讲，卢曼的这种做法是极其聪明的。认知科学家将人的信息加工分为两大
类，第一类是一阶操作，也就是@@html:<mark>@@“认知”本身@@html:</mark>@@，你感知的、
你记忆的、你学习的、你思考的。第二类是二阶操作，称之为@@html:<mark>@@“元认
知”@@html:</mark>@@，即对自己当前的认知进行监控：“我当前感知到了什么？我当前在记
忆什么？我当前在学习什么？我当前在思考什么？”这就是元感知、元记忆、元学习、元思
考等。“元认知”也就是认知的认知。

卢曼卡片盒写作法通过新增加的这个盒子，能够更好地对“元认知”的内容进行保存和加工。
一个盒子用于保存内容本身；一个盒子用于监控内容。

卢曼卡片盒写作法的高明之处还不仅于此。更重要的是，他让卡片与卡片通过各种索引关联
起来，从而提高了记忆提取的效率。
* 卢曼经常使用的索引可以分为四类
卢曼经常使用的索引可以分为以下四类。

第一类是主题索引。当某个主题的内容积累得足够丰富，卢曼就会做一张主题索引卡，对这
个主题进行概览。主题索引卡上会汇集所有相关笔记的编码或链接，每条笔记会用一两个词
或一个短句简要说明核心内容。这类索引，相当于给了你一个进入某一主题的入口。

第二类与主题索引类似，只不过不是对某一主题的概览，而是针对盒子里相近位置的卡片所
涉及的所有不同主题进行概览。

第三类是在当前卡片上做索引，标明这条笔记逻辑上的前一条是什么、后一条是什么（这些
卡片在盒子里的位置可能并不挨着）。

第四类，也是最常用的索引形式，就是简单的“笔记-笔记”连接。两条笔记可能完全没有关
系，把它们关联在一起，往往会产生出乎意料的新思路。

通过这些关联操作，我们能更好地对卡片内容进行组合、拼接、提取，从而产生更高质量的
内容。
