#+HUGO_BASE_DIR: ../
#+TITLE: Recording
#+DATE: <2021-05-06 Thu 01:42>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
About ZOOM https://www.zhihu.com/question/279930451/answer/411034575
* Best lossy audio formats
#+BEGIN_QUOTE
We spoke to Ben Westgarth, senior audio software engineer at NCH Software, about
the best lossy audio formats for archiving a music collection. He told us
there's a contentious debate about the topic among industry professionals and
casual users, but there is a clear winner in terms of file size to sound quality
ratio. "It is widely considered that AAC is a superior format - it can compress
to a smaller size for the same quality when compared to MP3."

The primary concern with converting to AAC instead of MP3 is compatibility with
media players. AAC was developed by a group of companies, including Nokia, Dolby
and Sony. It's promoted as a successor to the MP3 file format and is used by
huge streaming platforms such as Apple and YouTube. However, it still can't
match the ubiquitous device support that MP3 offers. Although AAC is a better
lossy format in terms of audio quality, Westgarth strongly suggests against
converting MP3 files to AAC. "In this scenario you are taking one lossy format
and re-compressing it into another, and it will only reduce the quality of your
audio - not improve it!" ([[https://www.toptenreviews.com/best-audio-converter-software][via]])
#+END_QUOTE
* Reference
- https://www.toptenreviews.com/best-audio-converter-software
- https://en.wikipedia.org/wiki/List_of_audio_conversion_software
