:PROPERTIES:
:ID:       7E9E8596-5111-4DA1-962B-B19FDAA09562
:END:
#+HUGO_BASE_DIR: ../
#+TITLE: Zettelkasten Note-taking Method
#+DATE: <2021-06-11 Fri 16:43>
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 
#+HUGO_CATEGORIES: 
#+HUGO_DRAFT: false
#+BEGIN_QUOTE
  The Zettelkasten method was made famous by Niklas Luhmann, who was a German
  sociologist who published over 70 books and 400 academic articles (Ahrens,
  2017, pp.30). Luhmann credited his achievements to his Zettelkasten, which
  contained over 90,000 ideas that helped him develop topics by knitting
  together ideas into a cohesive whole. His books wrote themselves, idea by
  idea. Even after his death, Luhmann's ideas were combined to publish more
  books on his behalf.

  The word Zettelkasten is German for "slip box", which refers to a box
  containing many slips of paper (Ahrens, 2017). Each slip represents a single,
  atomic idea that makes sense by itself, and also in combination with other
  ideas (similar to how our brain works, but with a better memory).
#+END_QUOTE
* Book
-> [[id:3A52CA13-DF1B-4D59-9D2A-13443460A43A][读《卡片笔记写作法》]]
* Reference
- https://www.youtube.com/watch?v=4veq2i3teVk&ab_channel=BielefeldUniversity
- https://www.youtube.com/watch?v=Pp3NMB9G7yY&ab_channel=CeheparCheng
- https://zettelkasten.de/introduction/
- https://www.youtube.com/watch?v=rOSZOCoqOo8
- https://medium.com/@rebeccawilliams9941/the-zettelkasten-method-examples-to-help-you-get-started-8f8a44fa9ae6
